import 'package:flutter/material.dart';

//Login Page
class ConditionOfUsePage extends StatefulWidget {
  const ConditionOfUsePage({super.key});

  @override
  State<ConditionOfUsePage> createState() => _ConditionOfUsePageState();
}

class _ConditionOfUsePageState extends State<ConditionOfUsePage> {
//final forgotPasswordEmail = TextEditingController();
  //final _logincardKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: null,
      body: SingleChildScrollView(
        child: Container(
          color: const Color(0xFFF5C418),
          child: const Padding(
            padding: EdgeInsets.all(20),
            child: Column(
              children: <Widget>[
                SizedBox(height: 20),
                Text(
                  'Certainly! Below are the Conditions of Use for this',
                  style: TextStyle(
                    color: Colors.black,
                    decoration: TextDecoration.none,
                    fontFamily: 'Roboto',
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    shadows: [
                      Shadow(
                        color: Color.fromARGB(255, 29, 29, 29), // Shadow color
                        offset: Offset(0, 4), // Position of the shadow
                        blurRadius: 8, // Spread radius of the shadow
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 20),
                Text(
                  //textAlign: TextAlign.justify,
                  '''
program :
  1. Acceptance of Terms: By using this program, you 
  agree to abide by these Conditions of Use. If you do 
  not agree with any part of these terms, please refrain 
  from using the program.
  2. Use of the Program :
    .• You may use this program for personal,non-
      commercial purposes.
    • You may not modify, distribute, or reverse engineer 
      the program without explicit permission.
  3. Privacy and Data Collection :
    • We respect your privacy. Any data collected during 
      your interaction with this program will be handled
      in accordance with our Privacy Policy.
    • We do not collect personally identifiable 
      information unless explicitly provided by you.
  4. Intellectual Property :
    • All content generated by this program is protected 
      by intellectual property laws.
    • You may not reproduce, distribute, or use this 
      content for commercial purposes without 
      permission.
  5. Disclaimer of Warranties :
    • This program is provided “as is” without any 
      warranties or guarantees.
    • We do not guarantee the accuracy, reliability, or 
      suitability of the content generated.
  6. Limitation of Liability :
    • We are not liable for any direct, indirect, incidental, 
      or consequential damages arising from the use of 
      this program.
  7.Termination : 
    • We reserve the right to terminate your access to 
      this program at any time without notice.
''',
                  style: TextStyle(
                      color: Colors.black,
                      decoration: TextDecoration.none,
                      fontFamily: 'Roboto',
                      fontSize: 15,
                      fontWeight: FontWeight.w300),
                ),
                SizedBox(height: 20),
                Text(
                  textAlign: TextAlign.justify,
                  '''Remember to use this program responsibly and enjoy the    
                                      experience! ✨''',
                  style: TextStyle(
                    color: Colors.black,
                    decoration: TextDecoration.none,
                    fontFamily: 'Roboto',
                    fontSize: 14,
                    fontWeight: FontWeight.w400,
                    shadows: [
                      Shadow(
                        color: Color.fromARGB(255, 83, 83, 83), // Shadow color
                        offset: Offset(0, 3), // Position of the shadow
                        blurRadius: 8, // Spread radius of the shadow
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
